version: "3.3"

services:
  starwarsapidb:
    image: mongo:latest
    restart: always
    container_name: starwarsapidb
    ports:
      - 27017:27017
  star-wars-api-image:
    image: star-wars-api-image
    container_name: star-wars-api-image
    restart: always
    ports:
      - 8080:8080
    links:
      - starwarsapidb
